export const APP_ROUTES = {
  root: "/",
  login: "/login",
  app: "/app",
  membership: "/app/membership",
  membershipDashboard: "/app/membership/dashboard",
  membershipTypes: "/app/membership/types",
  membershipMembers: "/app/membership/members",
  membershipPendingApprovals: "/app/membership/pending-approvals",
  membershipWizard: "/app/membership/wizard",
  membershipWizardTitle: "/app/membership/wizard/title",
  membershipWizardDescription: "/app/membership/wizard/description",
  membershipWizardColor: "/app/membership/wizard/color",
  membershipWizardBanner: "/app/membership/wizard/banner",
  membershipWizardPricing: "/app/membership/wizard/pricing",
  membershipWizardCustomForms: "/app/membership/wizard/custom-forms",
  membershipWizardThankYouEmail: "/app/membership/wizard/thank-you-email",
  membershipWizardAdvanceSettings: "/app/membership/wizard/advance-settings",
  membershipWizardReview: "/app/membership/wizard/review",
  customForms: "/app/custom-forms",
  customFormsCreate: "/app/custom-forms/create",
} as const;
