export const APP_ROUTES = {
  root: "/",
  login: "/login",
  app: "/",
  membership: "/membership/type",
  membershipDashboard: "/membership/type/dashboard",
  membershipTypes: "/membership/type/types",
  membershipMembers: "/membership/type/members",
  membershipPendingApprovals: "/membership/type/pending-approvals",
  membershipWizard: "/membership/type/wizard",
  membershipWizardTitle: "/membership/type/wizard/title",
  membershipWizardDescription: "/membership/type/wizard/description",
  membershipWizardColor: "/membership/type/wizard/color",
  membershipWizardBanner: "/membership/type/wizard/banner",
  membershipWizardPricing: "/membership/type/wizard/pricing",
  membershipWizardCustomForms: "/membership/type/wizard/custom-forms",
  membershipWizardThankYouEmail: "/membership/type/wizard/thank-you-email",
  membershipWizardAdvanceSettings: "/membership/type/wizard/advance-settings",
  membershipWizardReview: "/membership/type/wizard/review",
  customForms: "/organizer/custom-form/list",
  customFormsCreate: "/organizer/custom-form/create-form",
} as const;
